id: d6_robotstxt_settings
label: robots.txt 6 configuration
migration_tags:
  - Drupal 6
source:
  plugin: variable
  variables:
    - robotstxt
process:
  content: robotstxt
destination:
  plugin: config
  config_name: robotstxt.settings
