id: d7_robotstxt_settings
label: robots.txt 7 configuration
migration_tags:
  - Drupal 7
source:
  plugin: variable
  variables:
    - robotstxt
process:
  content: robotstxt
destination:
  plugin: config
  config_name: robotstxt.settings
